[package]
name = "rfcb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { version = "^0", features = [ "sqlx-postgres", "runtime-actix-rustls", "macros" ] }
dotenvy = "0.15"
actix-web = "4"
entity = { path = "entity" }
migration = { path = "migration" } # depends on your needs


[workspace]
members = [".", "entity", "migration"]

[profile.dev.package.sqlx-macros]
opt-level = 3


